# Vectors and Matrices in Numpy - Lab

## Introduction

This lab will ask you to perform some simple matrix creation and manipulation exercises based on what we have covered so far in this section. The key takeaway here for you is to be able to understand how to using indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays A (4x2) and B (2x3) 
```
A = 1402, 191 
    1371, 821 
    949, 1437
    147, 1448
    
B = 1, 2, 3
    4, 5, 6
    ```

In [1]:
import numpy as np

A = np.array([[1402, 191], [1371, 821], [949, 1437], [147, 1448]])
B = np.array([[1, 2, 3], [4, 5, 6]])

A, B

(array([[1402,  191],
        [1371,  821],
        [ 949, 1437],
        [ 147, 1448]]), array([[1, 2, 3],
        [4, 5, 6]]))

## 2. Print the dimensions of A and B 

In [4]:
print('Shape of A:', A.shape)
print('Shape of B:', B.shape)

Shape of A: (4, 2)
Shape of B: (2, 3)


## 3. Print some of the elements from A at following locations
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [8]:
print(A[0, 0])
print(A[0, 1])
print(A[2, 1])
print(A[3, 0])

1402
191
1437
147


## 4. Write a routine to populate matrix with random data
* Create an 3x3 numpy array with all zeros (use `np.zeros()`)
* Access each location i,j of this matrix and fill in random values between the range 1 and 10. 

In [76]:
def random_array(shape1, shape2):
    array = np.zeros((shape1, shape2))
    print('\nbefore random data:\n', array, '\n')
    for i in list(range(array.shape[0])):
        for j in list(range(array.shape[1])):
            array[i][j] = np.random.randint(1, high=10)
    print('after random data:\n', array)
    return array

rand_array = random_array(3, 3)
rand_array


before random data:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

after random data:
 [[5. 1. 6.]
 [6. 4. 1.]
 [8. 8. 3.]]


array([[5., 1., 6.],
       [6., 4., 1.],
       [8., 8., 3.]])

## 5. Turn above routine into a function.
* Create two 4x4 zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [82]:
rand_array_two = random_array(4, 4)
rand_array_three = random_array(4, 4)
combined_array = rand_array_two + rand_array_three

print('\nFinal output:\n', combined_array)


before random data:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

after random data:
 [[2. 3. 1. 4.]
 [3. 3. 8. 1.]
 [5. 6. 6. 4.]
 [3. 4. 8. 9.]]

before random data:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

after random data:
 [[1. 7. 7. 3.]
 [2. 1. 3. 7.]
 [9. 2. 3. 6.]
 [4. 7. 8. 5.]]

Final output:
 [[ 3. 10.  8.  7.]
 [ 5.  4. 11.  8.]
 [14.  8.  9. 10.]
 [ 7. 11. 16. 14.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 